set test "/set command"

send "/set default_action\\T\n"
expect {
    "name\tvalue\r\ndefault_action\tg\r\n\r\n"
    { pass "$test" }
}

send "/set default_action G\\T\n"
expect {
    "name\tvalue\r\ndefault_action\tG\r\n\r\n"
    { pass "$test" }
}

send "/set default_action g\\T\n"
expect {
    "name\tvalue\r\ndefault_action\tg\r\n\r\n"
    { pass "$test" }
}

send "/set foo\\T\n"
expect {
    "Variable not set\r\nname\tvalue\r\n\r\n"
    { pass "$test" }
}
